### ISSUE TITLE
[Bug] Xelphatol is fully broken

### ISSUE THREAD

**Issue by ghost** [ffxivcode/AutoDuty#716]
### What happened?

It does not find the path multiple times and wants to just fly upwards.
And even worse before it fights the last boss it leaves the dungeon.

### Version Number

0.0.0.181

### Steps to reproduce the error

Just run Xelaphtol, there is only one path.

**Comment by erdelf** [comment]
try `/vnav rebuild` in the dungeon. Sounds like your navmesh is broken

**Comment by ZyRage** [comment]
Used the command at the start of the dungeon -> after the 1. boss st the start of the inside of the mountain it tried to just fly up

Used the command again on that point -> it managed to go up to the elevator but is not able to get into the elevator, even after another use of the command it is stuck just here: https://prnt.sc/YAZKeJQ98dUS

After going into the elevator manually it get's stuck again inside the elevator as it wants to go into the other one: 
https://prnt.sc/YFUPrWGF_LuW

Another rebuild command later it wants to fly straight up to the next boss: https://prnt.sc/bNkLElTIpaDl

This only get's fixed with manually walking out of the elevator and doing another rebuild
Which then get stuck again at the next bigger plattform: https://prnt.sc/lzm40HQnkeuO

Another Rebuild later it goes back to the elevator and wants to go straight up there: 
https://prnt.sc/MtTSjQBtZ19C

After restarting the dungeon it manages to get to the elevator, but not inside the elevator.
It also skips the second boss in the AutoDuty steps after going manually into the elevator

**Comment by erdelf** [comment]
fixed in https://github.com/ffxivcode/AutoDuty/pull/719

**Comment by Gezahh** [comment]
The pathing works now without any problems
But the problem that AutoDuty leaves the dungeon before fighting the last boss still persists.

Directly after the boss cutscene would play it leaves the dungeons before engaging the fight
It works unsynched as you kill the trash before the boss fast enough is my guess
But with Duty Support it leaves after killing the last Trash

**Comment by erdelf** [comment]
I let it run 10 times with Duty Support before submitting it. Gonna need much more info.

**Comment by Gezahh** [comment]
I've run it three times now, in all three runs it left the dungeon before fighting the last boss
I recorded the last run, the video shows the last parts of the dungeon
At 1:40 the fight with the last trash "pack" starts and at 2:27 the pack dies and at 2:29 AD leaves the dungeon
https://youtu.be/RZI7gVfsHZ4

**Comment by erdelf** [comment]
huh.. 2 bosses right after another? yeah that will fuck with AD

**Comment by erdelf** [comment]
to clarify, the issue was that AD expected a boss, and then leave the duty.
But BossmodReborn made a module for the mini boss before the boss, so AD accepted that the mini boss is a boss.
The issue does not happen with BossMod (vbm), which I used for my tests, as it only has modules for the bosses.

Fixed in https://github.com/ffxivcode/AutoDuty/pull/731
